version: '3'

services:
  mm_ezstream4:
    build: .
    container_name: mm_ezstream4
    command: python3 ./main.py
    restart: unless-stopped
    ports:
      - "8001:8000"
    environment:
      - TZ=Europe/Samara
